version: '3.7'

services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        logging:
            options:
                max-size: 10m
                max-file: "3"

    webserver:
        build: .
        image: webserver
        container_name: webserver
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
            - NEWS_API_KEY=${NEWS_API_KEY}
            - API_TO_S3_ETL_BUCKET=${API_TO_S3_ETL_BUCKET}
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - ./src/dags:/usr/local/airflow/dags
            - ./src/tests:/usr/local/airflow/tests
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
